//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectorShopifySAP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TEST_DERMA")]
        public string CompanyDB {
            get {
                return ((string)(this["CompanyDB"]));
            }
            set {
                this["CompanyDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("manager")]
        public string UserSAP {
            get {
                return ((string)(this["UserSAP"]));
            }
            set {
                this["UserSAP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B1AdminH2")]
        public string PassSAP {
            get {
                return ((string)(this["PassSAP"]));
            }
            set {
                this["PassSAP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.61.28:50001/b1s/v1/")]
        public string urlSL {
            get {
                return ((string)(this["urlSL"]));
            }
            set {
                this["urlSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dermaexpress-dev.myshopify.com")]
        public string dominio {
            get {
                return ((string)(this["dominio"]));
            }
            set {
                this["dominio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2023-10")]
        public string api_v_shopify {
            get {
                return ((string)(this["api_v_shopify"]));
            }
            set {
                this["api_v_shopify"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("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")]
        public string TokenShopify {
            get {
                return ((string)(this["TokenShopify"]));
            }
            set {
                this["TokenShopify"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=172.16.61.28:30013;UserID=SYSTEM;Password=B1AdminH2;Database=NDB")]
        public string HanaConection {
            get {
                return ((string)(this["HanaConection"]));
            }
            set {
                this["HanaConection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("orders.json")]
        public string orderShopify {
            get {
                return ((string)(this["orderShopify"]));
            }
            set {
                this["orderShopify"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("orders.json?created_at_min=")]
        public string ordersShopifyByDate {
            get {
                return ((string)(this["ordersShopifyByDate"]));
            }
            set {
                this["ordersShopifyByDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/customers/")]
        public string customerShopify {
            get {
                return ((string)(this["customerShopify"]));
            }
            set {
                this["customerShopify"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01")]
        public string WhsCode {
            get {
                return ((string)(this["WhsCode"]));
            }
            set {
                this["WhsCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/admin/api/2023-10/variants/")]
        public string ProductVariant {
            get {
                return ((string)(this["ProductVariant"]));
            }
            set {
                this["ProductVariant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/admin/api/2023-10/graphql.json?")]
        public string graphql {
            get {
                return ((string)(this["graphql"]));
            }
            set {
                this["graphql"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("inventory_levels/adjust.json")]
        public string adjunst {
            get {
                return ((string)(this["adjunst"]));
            }
            set {
                this["adjunst"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("66487746780")]
        public string location_id {
            get {
                return ((string)(this["location_id"]));
            }
            set {
                this["location_id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orders")]
        public string OrdersSAP {
            get {
                return ((string)(this["OrdersSAP"]));
            }
            set {
                this["OrdersSAP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/metafields.json")]
        public string metafields {
            get {
                return ((string)(this["metafields"]));
            }
            set {
                this["metafields"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Invoices")]
        public string InvoiceSAP {
            get {
                return ((string)(this["InvoiceSAP"]));
            }
            set {
                this["InvoiceSAP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IncomingPayments")]
        public string IncomingPayments {
            get {
                return ((string)(this["IncomingPayments"]));
            }
            set {
                this["IncomingPayments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("products.json")]
        public string Product {
            get {
                return ((string)(this["Product"]));
            }
            set {
                this["Product"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string ListPrices {
            get {
                return ((string)(this["ListPrices"]));
            }
            set {
                this["ListPrices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/admin/api/2023-10/inventory_levels/adjust.json")]
        public string inventory_levels {
            get {
                return ((string)(this["inventory_levels"]));
            }
            set {
                this["inventory_levels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public string UnidadNegocio {
            get {
                return ((string)(this["UnidadNegocio"]));
            }
            set {
                this["UnidadNegocio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("idsap")]
        public string metafieldSAP {
            get {
                return ((string)(this["metafieldSAP"]));
            }
            set {
                this["metafieldSAP"] = value;
            }
        }
    }
}
